name = "classificador-imagens-cloudflare"
main = "functions/[[path]].js"
compatibility_date = "2024-11-01"

# Bind do R2
[[r2_buckets]]
binding = "BUCKET"            # como será acessado no código
bucket_name = "images-bucket" # crie antes no painel ou via CLI

[vars]
IMAGES_PREFIX = "images/"
KEEP_PREFIX = "keep/"
TRASH_PREFIX = "trash/"
ALLOWED_EXT = "jpg,jpeg,png,webp,gif,bmp,tiff,avif"
PERMANENT_DELETE = "false"
